---
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
    checks:
      TODO:
        enabled: false
  radon:
    enabled: true
    config: 
      python_version: 2
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths: []
