language: java
notifications:
  hipchat:
    rooms:
      secure: ZiSyGwuy09O35VDhaUUtAIg3Feqx1vcmustxIEGL32+W6Dbw/UjhLWXsQofgPN0EFXcwpe9R7IyolYECQGBPrh75ftgnRZ7NOYdli3bdcudhLFLeiOvtP57274BWx+rMAOA8sk4CDvV/keToqxJlZ2RLSBoWGK/qwjtu0oP/jizuZ1BiFvOSppW7pj189lCidJdoRwpnr2/Ee4j9A0iTSmWRztriwMvfvL1Euyr8PP8xVKgypKKXtOT9kcl22k8T9dl35ps/D/FK/qhGXJEFjpSo2a1XniaQiw5zNr1m4ACrt7lChyHeKZYRHZD7A706OxAdkgzch33OcIi5IFpH7QtEDGUhWclaA7j3D48w9cJ8SP5RNOoxQ/kKso7Q9EQ+6Ism6rGr6R62KWUbCTM2/+cntOVJ97nzL9GOLOOt+YFLbBjLyPMEdj0xrw+CSVtmfNzJ6rT6MeXbhwSvRm3mB31mDHBE0fmMdHvr6ZEo76b169QSfdR6C4Di5dENrsMzobiL83T6pPksHweTdoTFfyx3Wk9rkp2iwWrb8saZOKm9H9ZwFLRhNbU3stj6LVjtZJArf3aAwLFlIqgGWnDL2HH7O01lXFXtZyJ+licNMWasOyCV4uP75ZHMIA6/v9V5UNCUNTdhE7vHRJbWmXQz+WNb+OlNqQcv0mc3nFADXkQ=
    on_success: always
    on_failure: always
deploy:
  provider: releases
  api-key:
    secure: WZgga57mmpfqbex4tc3WynxscGhV7xftItoFgrz23rtK7Ftkfdh/x72iEdyvkMZBArtS3OLooSPoT76qDeylPs5n5EWNDj3H6if98hPREB84C+YJ1YQuakvSxXq7ydPiWLAd+LYInmNgdPxYc3m2XMJqzpg4Pk85H3EeS4uJ6IkBY7AlFU31Q6QYTZVPeGq4DPlWKPNgbySCkkZYtZ9QK1/hBsG+NP0dUf3Pce1SSWYuNGiZn85CEtBhPHGA3N4EMThqZB49VJ17rYUz8ALtU6idds35w3DFx1umanfeXVLJpIWX27AXkHBwxJWm4bELpktRhg4PTMupU+mxuPxwEMyOt0HSWbXGrMQtdMWMBO61uC0jAR7rleconB2MySuXSjdaUVWcwHEblbLKkc7ty6fkiAQS56Fb8kMKOT8AtNzcWzaajYbpTZ0joB7MiPxsdGbjEV6st7KBjPKews58xscIfLpoQXIOrEjIqFPsuACttOcitFZh3BsMbyon+zDCzgDh6SL6Hc16r1GgpRqevWQ7kJy/DsLWNqaLKYxuAGrt6zWrdS32rsSEVLpiUiWaLUWGfdKuE0H3AByIh/KTCwYiW7ERtmpZIUDbhJXpP7HgunjfUZsDpeO2MgJasAgDW7EYVZiGC1gT0Y5W7/RfdQyBbEUi1jXYw3Km8AjHNGs=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: xebialabs-community/xlr-bitbucket-plugin
