language: java
notifications:
  hipchat:
    rooms:
      secure: ZiSyGwuy09O35VDhaUUtAIg3Feqx1vcmustxIEGL32+W6Dbw/UjhLWXsQofgPN0EFXcwpe9R7IyolYECQGBPrh75ftgnRZ7NOYdli3bdcudhLFLeiOvtP57274BWx+rMAOA8sk4CDvV/keToqxJlZ2RLSBoWGK/qwjtu0oP/jizuZ1BiFvOSppW7pj189lCidJdoRwpnr2/Ee4j9A0iTSmWRztriwMvfvL1Euyr8PP8xVKgypKKXtOT9kcl22k8T9dl35ps/D/FK/qhGXJEFjpSo2a1XniaQiw5zNr1m4ACrt7lChyHeKZYRHZD7A706OxAdkgzch33OcIi5IFpH7QtEDGUhWclaA7j3D48w9cJ8SP5RNOoxQ/kKso7Q9EQ+6Ism6rGr6R62KWUbCTM2/+cntOVJ97nzL9GOLOOt+YFLbBjLyPMEdj0xrw+CSVtmfNzJ6rT6MeXbhwSvRm3mB31mDHBE0fmMdHvr6ZEo76b169QSfdR6C4Di5dENrsMzobiL83T6pPksHweTdoTFfyx3Wk9rkp2iwWrb8saZOKm9H9ZwFLRhNbU3stj6LVjtZJArf3aAwLFlIqgGWnDL2HH7O01lXFXtZyJ+licNMWasOyCV4uP75ZHMIA6/v9V5UNCUNTdhE7vHRJbWmXQz+WNb+OlNqQcv0mc3nFADXkQ=
    on_success: always
    on_failure: always
deploy:
  provider: releases
  api-key:
    secure: YeEJO7TElGtHfVxI/uhujcrGRhhI9w6GvBh67jPHGoIP0+G5TnUs2rhKMnhqxNkMGLDuCcm+U5QTQDAFOVoERlQPSqlTHF7bohxaJujTDZ+es9QHjUqsy2/CT/ov//m6gmFUPplLW++gOmABZR1WoOWp2eT1H/1NDDsT5jAI7wrQchjTlLEQndaCP8tAHI9hD4VdXiF38+1OYP55d/Tmujs3KpKDx2Df3f+12twhjGIwg+7kTaoAdN7j+TD0uUoSZ7wby98KUnAn5qj+dq0cfYoc2kvZ+eMEzxQpMXzxuWlFXOUwb2j9AFzR2SMC38BJxgHU92e3XnfbZP4mFOLpQLJnW1HUdPQQdAAebvpomDjvTsg3H8ttmoNj43eBhRwVVgA3ER2btEdsJGsrYZbkRftGoNi6irL14ymNxLY9VtnayyUCSXbEgZZgY/XUpNnlULEGvwpfg5ZYMtMMlJZDxImrIipEoiNOXjVO8GYOVk5mKA8YQ+Bv+5tQlopDasFMI+NFFVneVU205+ZGcCV2DlAnkBRO+6E5oy6vyDpnj2SD4wEQ1PKWtjEfA5OF6eKz/vvTP9FsdmjwQONmM2E09Jv4Y6N/ktIcX+XbI2OlpK3926bSBh+MtIPLa4Do0UOM3+KcR8fScRL0b3uHEKebFg997NGoQxbEGh0QllLq0n4=
  file: build/libs/xlr-bitbucket-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: xebialabs-community/xlr-bitbucket-plugin
